{
 "title": "acrss",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "patient",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"acrss\",\r\n  tag: \"patient_id\"\r\n)\r\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "vitals parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RESPIRATION RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vitals_state\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.sensor == \"rr\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> yield(name: \"RR\")\r\n"
    }
   ]
  },
  {
   "title": "MEAN ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vitals_state\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.sensor == \"rr\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> mean()\r\n"
    }
   ]
  },
  {
   "title": "SpO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vitals_state\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.sensor == \"spo2\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> yield(name: \"SpO2\")\r\n"
    }
   ]
  },
  {
   "title": "MEAN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vitals_state\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.sensor == \"spo2\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> mean()\r\n"
    }
   ]
  },
  {
   "title": "HEART RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vitals_state\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.sensor == \"hr\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> yield(name: \"HR\")\r\n"
    }
   ]
  },
  {
   "title": "MEAN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vitals_state\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r.sensor == \"hr\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> mean()\r\n"
    }
   ]
  },
  {
   "title": "BLOOD PRESSURE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vitals_state\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> filter(fn: (r) => r._field == \"value_sbp\" or r._field == \"value_dbp\")\r\n  |> yield(name: \"BP\")\r\n"
    }
   ]
  },
  { "title": "symptoms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "SYMPTOMS",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"symptoms\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> filter(fn: (r) =>\r\n      r._field == \"status_oxigenation\" or\r\n      r._field == \"status_respiration\" or\r\n      r._field == \"status_heart_rate\" or\r\n      r._field == \"status_blood_pressure\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "TREND",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"symptoms\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> filter(fn: (r) =>\r\n      r._field == \"trend_hr\" or\r\n      r._field == \"trend_spo2\" or\r\n      r._field == \"trend_map\" or\r\n      r._field == \"trend_rr\"\r\n  )\r\n"
    }
   ]
  },
  {
   "title": "INTENSITY",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"symptoms\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> filter(fn: (r) =>\r\n      r._field == \"intensity_hr\" or\r\n      r._field == \"intensity_spo2\" or\r\n      r._field == \"intensity_map\" or\r\n      r._field == \"intensity_rr\"\r\n  )\r\n\r\n"
    }
   ]
  },
  { "title": "therapies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "OXIGENATION THERAPY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "flowmlpm" } },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"therapies\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> filter(fn: (r) => r._field == \"ox_therapy\")\r\n"
    }
   ]
  },
  {
   "title": "FLUIDS",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"therapies\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> filter(fn: (r) => r._field == \"has_fluids\")\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _value: if r._value == 1 then \"BOLUS\" else \"STOP\"\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "BETA BLOCKING",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "query": "from(bucket: \"acrss\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"therapies\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient}\")\r\n  |> filter(fn: (r) => r._field == \"carvedilolo_beta_blocking\")\r\n"
    }
   ]
  }
 ]
}